//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubsidioEntities : DbContext
    {
        public SubsidioEntities()
            : base("name=SubsidioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ESTADO_CIVIL> ESTADO_CIVIL { get; set; }
        public DbSet<GENERO> GENERO { get; set; }
        public DbSet<NACIONALIDAD> NACIONALIDAD { get; set; }
        public DbSet<POSTULANTE> POSTULANTE { get; set; }
        public DbSet<PUNTAJE_CARGA_FAMILIAR> PUNTAJE_CARGA_FAMILIAR { get; set; }
        public DbSet<PUNTAJE_EDAD> PUNTAJE_EDAD { get; set; }
        public DbSet<PUNTAJE_ESTADO_CIVIL> PUNTAJE_ESTADO_CIVIL { get; set; }
        public DbSet<PUNTAJE_MONTO_AHORRO> PUNTAJE_MONTO_AHORRO { get; set; }
        public DbSet<PUNTAJE_PUEBLO_ORIGINARIO> PUNTAJE_PUEBLO_ORIGINARIO { get; set; }
        public DbSet<PUNTAJE_TITULO> PUNTAJE_TITULO { get; set; }
        public DbSet<PUNTAJE_ZONA_EXTREMA> PUNTAJE_ZONA_EXTREMA { get; set; }
        public DbSet<RECEPTOR> RECEPTOR { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<TITULO> TITULO { get; set; }
    }
}
