//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTULANTE
    {
        public string RUN_POSTULANTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public int MONTO_AHORRO { get; set; }
        public string PUEBLO_ORIGINARIO { get; set; }
        public int CARGAS_FAMILIARES { get; set; }
        public int ID_NACIONALIDAD { get; set; }
        public int ID_ESTADO_CIVIL { get; set; }
        public int ID_GENERO { get; set; }
        public int ID_REGION { get; set; }
        public int ID_RECEPTOR { get; set; }
        public int ID_TITULO { get; set; }
    
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual NACIONALIDAD NACIONALIDAD { get; set; }
        public virtual RECEPTOR RECEPTOR { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual TITULO TITULO { get; set; }
    }
}
