//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTAJE_POSTULANTE
    {
        public int ID_PUNTAJE { get; set; }
        public int CARGA_FAMILIAR { get; set; }
        public int AHORRO { get; set; }
        public int TITULO { get; set; }
        public int EDAD { get; set; }
        public int PUEBLO_ORIGINARIO { get; set; }
        public int ESTADO_CIVIL { get; set; }
        public int REGION { get; set; }
        public int TOTAL_PUNTAJE { get; set; }
        public string RUN_POSTULANTE { get; set; }
    
        public virtual POSTULANTE POSTULANTE { get; set; }
    }
}
