//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTAJE_TITULO
    {
        public decimal ID_PUNTAJE_TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PUNTAJE { get; set; }
    }
}
