//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTAJE_MONTO_AHORRO
    {
        public decimal ID_PUNTAJE_MONTO_AHORRO { get; set; }
        public decimal MONTO_SUP { get; set; }
        public decimal MONTO_INF { get; set; }
        public decimal PUNTAJE { get; set; }
    }
}
