//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTAJE_CARGA_FAMILIAR
    {
        public decimal ID_PUNTAJE_CARGA_FAMILIAR { get; set; }
        public decimal CARGA_INF { get; set; }
        public decimal CARGA_SUP { get; set; }
        public decimal PUNTAJE { get; set; }
    }
}
