//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTAJE_TOTAL
    {
        public string RUN_POSTULANTE { get; set; }
        public int PUNTAJE { get; set; }
    
        public virtual POSTULANTE POSTULANTE { get; set; }
    }
}
