//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TESTING
    {
        public string RUT_POSTULANTE { get; set; }
        public string NOMBRE_POSTULANTE { get; set; }
        public Nullable<decimal> EDAD { get; set; }
        public Nullable<decimal> PUNTAJE_EDAD { get; set; }
        public decimal CARGAS_FAMILIARES { get; set; }
        public Nullable<decimal> PUNTAJE_CARGAS_FAMILIARES { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public Nullable<decimal> PUNTAJE_ESTADO_CIVIL { get; set; }
        public string PUEBLO_ORIGINARIO { get; set; }
        public Nullable<decimal> PUNTAJE_PUEBLO { get; set; }
        public decimal MONTO_AHORRO { get; set; }
        public Nullable<decimal> PUNTAJE_MONTO_AHORRO { get; set; }
        public string TITULO { get; set; }
        public Nullable<decimal> PUNTAJE_TITULO { get; set; }
        public string ZONA { get; set; }
        public Nullable<decimal> PUNTAJE_ZONA { get; set; }
        public string TIPO_VIVIENDA { get; set; }
        public decimal VALOR_VIVIENDA { get; set; }
        public Nullable<decimal> PUNTAJE_TOTAL { get; set; }
    }
}
